# Site settings
title: RayHightower.com
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about Ruby, iOS, the Internet of Things, and business growth.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rayhightower.com" # the base hostname & protocol for your site
twitter_username: RayHightower
github_username:  RayHightower

# Build settings
markdown: redcarpet
highlighter: pygments

